// packages/core/src/pages/search/react/search-results/SearchResults.tsx
import type { FC } from 'react';

import { SearchResultsItem } from './SearchResultsItem';
import { searchResults } from '../../mocks';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';
import { PharosDropdownMenu } from '../../../../react-components/dropdown-menu/pharos-dropdown-menu';
import { PharosDropdownMenuItem } from '../../../../react-components/dropdown-menu/pharos-dropdown-menu-item';
import { PharosButton } from '../../../../react-components/button/pharos-button';
import { PharosPagination } from '../../../../react-components/pagination/pharos-pagination';

export const SearchResults: FC = () => (
  <div className="search-page__container--search-results">
    <div className="search-page__container--results-top-bar">
      <PharosHeading level={3} preset="2">
        721,120 text results
      </PharosHeading>
      <PharosButton
        variant="secondary"
        iconRight="chevron-down"
        data-dropdown-menu-id="sort-dropdown"
        style={{ marginLeft: 'auto' }}
      >
        Sort by: Relevance
      </PharosButton>
    </div>
    <PharosDropdownMenu id="sort-dropdown" showSelected fullWidth>
      <PharosDropdownMenuItem selected>Relevance</PharosDropdownMenuItem>
      <PharosDropdownMenuItem>Newest</PharosDropdownMenuItem>
      <PharosDropdownMenuItem>Oldest</PharosDropdownMenuItem>
    </PharosDropdownMenu>
    <ol className="search-page__list--results">
      {searchResults.map((result, index) => (
        <li key={index} className="search-page__list-item--results">
          {SearchResultsItem(result)}
        </li>
      ))}
    </ol>
    <div className="search-page__container--results-pagination">
      <PharosPagination
        totalResults={132}
        pageSize={4}
        currentPage={1}
        style={{ marginLeft: 'auto' }}
      ></PharosPagination>
    </div>
  </div>
);

// packages/pharos/src/pages/search/wc/search-results/search-results.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';

import { SearchResultsItem } from './search-results-item';
import '../../../../components/heading/pharos-heading';
import '../../../../components/button/pharos-button';
import '../../../../components/dropdown-menu/pharos-dropdown-menu';
import '../../../../components/dropdown-menu/pharos-dropdown-menu-item';
import '../../../../components/pagination/pharos-pagination';
import { searchResults } from '../../mocks';

export const SearchResults = (): TemplateResult => html`
  <div class="search-page__container--search-results">
    <div class="search-page__container--results-top-bar">
      <pharos-heading level="3" preset="2">721,120 text results</pharos-heading>
      <pharos-button
        variant="secondary"
        icon-right="chevron-down"
        data-dropdown-menu-id="sort-dropdown"
        style="margin-left: auto"
        >Sort by: Relevance</pharos-button
      >
    </div>
    <pharos-dropdown-menu id="sort-dropdown" show-selected full-width>
      <pharos-dropdown-menu-item selected>Relevance</pharos-dropdown-menu-item>
      <pharos-dropdown-menu-item>Newest</pharos-dropdown-menu-item>
      <pharos-dropdown-menu-item>Oldest</pharos-dropdown-menu-item>
    </pharos-dropdown-menu>
    <ol class="search-page__list--results">
      ${searchResults.map(
        (result) =>
          html`<li class="search-page__list-item--results">${SearchResultsItem(result)}</li>`
      )}
    </ol>
    <div class="search-page__container--results-pagination">
      <pharos-pagination
        total-results="132"
        page-size="4"
        current-page="1"
        style="margin-left: auto"
      ></pharos-pagination>
    </div>
  </div>
`;
