// packages/pharos/src/pages/home/wc/collection-card.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';
import type { Card } from '../types';

import '../../../components/link/pharos-link';
import '../../../components/heading/pharos-heading';

export const CollectionCard = (card: Card): TemplateResult => html`
  <div>
    <img
      src="./images/home/${card.image}"
      alt="${card.title}"
      width="99.9%"
      class="home-page__image--collection"
    />
    <pharos-heading level="2" preset="3">${card.title}</pharos-heading>
    <pharos-link href="#">${card.link}</pharos-link>
  </div>
`;

// packages/pharos/src/pages/home/react/CollectionCard.tsx
import type { FC } from 'react';
import type { Card } from '../types';

import { PharosLink } from '../../../react-components/link/pharos-link';
import { PharosHeading } from '../../../react-components/heading/pharos-heading';

export const CollectionCard: FC<Card> = ({ title, link, image }) => (
  <div>
    <img
      src={`./images/home/${image}`}
      alt={title}
      width="99.9%"
      className="home-page__image--collection"
    />
    <PharosHeading level={2} preset="3">
      {title}
    </PharosHeading>
    <PharosLink href="#">{link}</PharosLink>
  </div>
);
