// packages/core/src/pages/home/wc/hero-search.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';

import '../../../components/icon/pharos-icon';

export const HeroSearch = (): TemplateResult => html`
  <div class="home-page__container--input">
    <pharos-icon name="search" class="home-page__icon--search"></pharos-icon>
    <input class="home-page__input" placeholder="Search JSTOR..." />
  </div>
`;

// packages/pharos/src/pages/home/react/HeroSearch.tsx
import type { FC } from 'react';

import { PharosIcon } from '../../../react-components/icon/pharos-icon';

export const HeroSearch: FC = () => (
  <div className="home-page__container--input">
    <PharosIcon name="search" className="home-page__icon--search"></PharosIcon>
    <input className="home-page__input" placeholder="Search JSTOR..." />
  </div>
);
