// packages/core/src/pages/search/react/facets/DateRangeFacet.tsx
import type { FC } from 'react';

import { PharosHeading } from '../../../../react-components/heading/pharos-heading';
import { PharosButton } from '../../../../react-components/button/pharos-button';
import { PharosTextInput } from '../../../../react-components/text-input/pharos-text-input';

export const DateRangeFacet: FC = () => (
  <fieldset className="search-page__fieldset--date">
    <legend>
      <PharosHeading level={3} preset="legend">
        Date
      </PharosHeading>
    </legend>
    <small className="search-page__text--description">(YYYY, YYYY/MM or YYYY/MM/DD)</small>
    <div className="search-page__grid--date">
      <PharosTextInput name="from">
        <span slot="label">From</span>
      </PharosTextInput>
      <PharosTextInput name="to">
        <span slot="label">To</span>
      </PharosTextInput>
      <PharosButton disabled>Apply</PharosButton>
    </div>
  </fieldset>
);

// packages/pharos/src/pages/search/wc/facets/date-range-facet.ts
import { html } from 'lit';
import type { TemplateResult } from 'lit';

import '../../../../components/text-input/pharos-text-input';
import '../../../../components/button/pharos-button';
import '../../../../components/heading/pharos-heading';

export const DateRangeFacet = (): TemplateResult => html`
  <fieldset class="search-page__fieldset--date">
    <legend>
      <pharos-heading level="3" preset="legend">Date</pharos-heading>
    </legend>
    <small class="search-page__text--description">(YYYY, YYYY/MM or YYYY/MM/DD)</small>
    <div class="search-page__grid--date">
      <pharos-text-input name="from">
        <span slot="label">From</span>
      </pharos-text-input>
      <pharos-text-input name="to">
        <span slot="label">To</span>
      </pharos-text-input>
      <pharos-button disabled>Apply</pharos-button>
    </div>
  </fieldset>
`;
