// packages/pharos/src/pages/search/react/facets/MultiSelectFacet.tsx
import type { FC } from 'react';
import type { CheckboxGroupItem } from '../../types';

import { PharosCheckbox } from '../../../../react-components/checkbox/pharos-checkbox';
import { PharosCheckboxGroup } from '../../../../react-components/checkbox-group/pharos-checkbox-group';

interface MultiSelectFacetProps {
  name: string;
  legend: string;
  items: CheckboxGroupItem[];
}

export const MultiSelectFacet: FC<MultiSelectFacetProps> = ({ name, legend, items }) => (
  <PharosCheckboxGroup name={name}>
    <span slot="legend">{legend}</span>
    {items.map((item, index) => (
      <PharosCheckbox key={index} value={item.value}>
        <span slot="label">{item.label}</span>
      </PharosCheckbox>
    ))}
  </PharosCheckboxGroup>
);

// packages/pharos/src/pages/search/wc/facets/multi-select-facet.ts
import { html } from 'lit';
import type { TemplateResult } from 'lit';
import type { CheckboxGroupItem } from '../../types';

import '../../../../components/checkbox-group/pharos-checkbox-group';
import '../../../../components/checkbox/pharos-checkbox';

export const MultiSelectFacet = (
  name: string,
  legend: string,
  items: CheckboxGroupItem[]
): TemplateResult => html`
  <pharos-checkbox-group name="${name}">
    <span slot="legend">${legend}</span>
    ${items.map(
      (item) =>
        html`<pharos-checkbox value="${item.value}"
          ><span slot="label">${item.label}</span></pharos-checkbox
        >`
    )}
  </pharos-checkbox-group>
`;
