// packages/pharos/src/pages/search/react/facets/SingleSelectFacet.tsx
import type { FC } from 'react';
import type { RadioGroupItem } from '../../types';

import { PharosRadioButton } from '../../../../react-components/radio-button/pharos-radio-button';
import { PharosRadioGroup } from '../../../../react-components/radio-group/pharos-radio-group';

interface SingleSelectFacetProps {
  name: string;
  legend: string;
  items: RadioGroupItem[];
}

export const SingleSelectFacet: FC<SingleSelectFacetProps> = ({ name, legend, items }) => (
  <PharosRadioGroup name={name}>
    <span slot="legend">{legend}</span>
    {items.map((item, index) => (
      <PharosRadioButton key={index} value={item.value}>
        <span slot="label">{item.label}</span>
      </PharosRadioButton>
    ))}
  </PharosRadioGroup>
);

// packages/pharos/src/pages/search/wc/facets/single-select-facet.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';
import type { RadioGroupItem } from '../../types';

import '../../../../components/radio-group/pharos-radio-group';
import '../../../../components/radio-button/pharos-radio-button';

export const SingleSelectFacet = (
  name: string,
  legend: string,
  items: RadioGroupItem[]
): TemplateResult => html`
  <pharos-radio-group name="${name}">
    <span slot="legend">${legend}</span>
    ${items.map(
      (item) =>
        html`<pharos-radio-button value="${item.value}"
          ><span slot="label">${item.label}</span></pharos-radio-button
        >`
    )}
  </pharos-radio-group>
`;
