// packages/pharos/src/pages/item-detail/wc/collection-carousel/collection-carousel-item.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';
import type { Collection } from '../../types';

import '../../../../components/link/pharos-link';
import '../../../../components/heading/pharos-heading';

export const CollectionCarouselItem = (collection: Collection): TemplateResult => html`
  <pharos-link href="#" subtle flex>
    <div class="item-detail-page__grid--carousel-item item-detail-page__grid--open-collection">
      <img src="./images/storybook/item-detail/${collection.image}" alt="${collection.title}" />
      <pharos-heading preset="1--bold" level="3" no-margin>${collection.title}</pharos-heading>
    </div>
  </pharos-link>
  <span class="item-detail-page__text--collection-items">${collection.items} items</span>
`;

// packages/pharos/src/pages/item-detail/react/collection-carousel/CollectionCarouselItem.tsx
import type { FC } from 'react';
import { Fragment } from 'react';
import type { Collection } from '../../types';

import { PharosLink } from '../../../../react-components/link/pharos-link';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';

export const CollectionCarouselItem: FC<Collection> = (collection) => (
  <Fragment>
    <PharosLink href="#" subtle flex>
      <div className="item-detail-page__grid--carousel-item item-detail-page__grid--open-collection">
        <img src={`./images/storybook/item-detail/${collection.image}`} alt={collection.title} />
        <PharosHeading preset="1--bold" level={3} noMargin>
          {collection.title}
        </PharosHeading>
      </div>
    </PharosLink>
    <span className="item-detail-page__text--collection-items">{collection.items} items</span>
  </Fragment>
);
