// packages/core/src/pages/item-detail/wc/collection-carousel/collection-carousel.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';

import { CollectionCarouselItem } from './collection-carousel-item';
import { collections } from '../../mocks';

import '../../../../components/heading/pharos-heading';
import '../../../../components/button/pharos-button';

export const CollectionCarousel = (): TemplateResult => html`
  <div class="item-detail-page__container--top-bar">
    <pharos-heading level="2" preset="3" no-margin>Explore our open collections</pharos-heading>
    <div class="item-detail-page__container--carousel-buttons">
      <pharos-button
        label="backward"
        variant="subtle"
        icon="chevron-left-large"
        icon-condensed
      ></pharos-button>
      <pharos-button
        label="forward"
        variant="subtle"
        icon="chevron-right-large"
        icon-condensed
      ></pharos-button>
    </div>
  </div>
  <ul class="item-detail-page__list item-detail-page__grid--collections">
    ${collections.map((collection) => html`<li>${CollectionCarouselItem(collection)}</li>`)}
  </ul>
`;

// packages/pharos/src/pages/item-detail/react/collection-carousel/CollectionCarousel.tsx
import type { FC } from 'react';
import { Fragment } from 'react';

import { CollectionCarouselItem } from './CollectionCarouselItem';
import { collections } from '../../mocks';

import { PharosButton } from '../../../../react-components/button/pharos-button';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';

export const CollectionCarousel: FC = () => (
  <Fragment>
    <div className="item-detail-page__container--top-bar">
      <PharosHeading level={2} preset="3" noMargin>
        Explore our open collections
      </PharosHeading>
      <div className="item-detail-page__container--carousel-buttons">
        <PharosButton
          a11y-label="backward"
          variant="subtle"
          icon="chevron-left-large"
          iconCondensed
        ></PharosButton>
        <PharosButton
          a11y-label="forward"
          variant="subtle"
          icon="chevron-right-large"
          iconCondensed
        ></PharosButton>
      </div>
    </div>
    <ul className="item-detail-page__list item-detail-page__grid--collections">
      {collections.map((collection, index) => (
        <li key={index}>{CollectionCarouselItem(collection)}</li>
      ))}
    </ul>
  </Fragment>
);
