// packages/core/src/pages/search/wc/image-results/image-results-item.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';
import type { ImageResult } from '../../types';

import '../../../../components/link/pharos-link';
import '../../../../components/heading/pharos-heading';

export const ImageResultsItem = (result: ImageResult): TemplateResult => html`
  <pharos-link href="#" subtle flex>
    <div class="search-page__grid--image">
      <img src="./images/storybook/search/${result.image}" alt="${result.title}" width="99%" />
      <pharos-heading preset="1--bold" level="3" no-margin>${result.title}</pharos-heading>
    </div>
  </pharos-link>
`;

// packages/pharos/src/pages/search/react/image-results/ImageResultsItem.tsx
import type { FC } from 'react';
import type { ImageResult } from '../../types';

import { PharosLink } from '../../../../react-components/link/pharos-link';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';

export const ImageResultsItem: FC<ImageResult> = ({ title, image }) => (
  <PharosLink href="#" subtle flex>
    <div className="search-page__grid--image">
      <img src={`./images/storybook/search/${image}`} alt={title} width="99%" />
      <PharosHeading preset="1--bold" level={3} noMargin>
        {title}
      </PharosHeading>
    </div>
  </PharosLink>
);
