// packages/pharos/src/pages/item-detail/react/item-carousel/ItemCarouselItem.tsx
import type { FC } from 'react';
import { Fragment } from 'react';
import type { Item } from '../../types';

import { PharosLink } from '../../../../react-components/link/pharos-link';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';

export const ItemCarouselItem: FC<Item> = (item) => (
  <Fragment>
    <PharosLink href="#" subtle flex>
      <div className="item-detail-page__grid--carousel-item">
        <img src={`./images/item-detail/${item.image}`} alt={item.title} />
        <PharosHeading preset="1--bold" level={3} noMargin>
          {item.title}
        </PharosHeading>
      </div>
    </PharosLink>
    <span className="item-detail-page__text--item-metadata">{item.metadata}</span>
  </Fragment>
);

// packages/pharos/src/pages/item-detail/wc/item-carousel/item-carousel-item.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';
import type { Item } from '../../types';

import '../../../../components/link/pharos-link';
import '../../../../components/heading/pharos-heading';

export const ItemCarouselItem = (item: Item): TemplateResult => html`
  <pharos-link href="#" subtle flex>
    <div class="item-detail-page__grid--carousel-item">
      <img src="./images/item-detail/${item.image}" alt="${item.title}" />
      <pharos-heading preset="1--bold" level="3" no-margin>${item.title}</pharos-heading>
    </div>
  </pharos-link>
  <span class="item-detail-page__text--item-metadata">${item.metadata}</span>
`;
