// packages/pharos/src/pages/reports/wc/sidenav.ts
import { html } from 'lit-html';
import type { TemplateResult } from 'lit-html';

import '../../../components/sidenav/pharos-sidenav';
import '../../../components/sidenav/pharos-sidenav-section';
import '../../../components/sidenav/pharos-sidenav-link';
import '../../../components/sidenav/pharos-sidenav-menu';
import '../../../components/link/pharos-link';

export const Sidenav = (): TemplateResult => html`
  <pharos-sidenav class="reports-page__sidenav">
    <pharos-link slot="top" href="/" id="jstor-logo">
      <img src="./images/jstor-logo-inverse.svg" alt="Pharos Home" width="72" height="100" />
    </pharos-link>
    <pharos-sidenav-section>
      <pharos-sidenav-link href="#">Home</pharos-sidenav-link>
      <pharos-sidenav-menu label="Reports" expanded>
        <pharos-sidenav-link href="#" is-active>COUNTER 5</pharos-sidenav-link>
        <pharos-sidenav-link href="#">Books at JSTOR</pharos-sidenav-link>
        <pharos-sidenav-link href="#">COUNTER 4</pharos-sidenav-link>
      </pharos-sidenav-menu>
      <pharos-sidenav-link href="#">Holdings</pharos-sidenav-link>
      <pharos-sidenav-link href="#">Access Methods</pharos-sidenav-link>
      <pharos-sidenav-link href="#">Account</pharos-sidenav-link>
      <pharos-sidenav-link href="#" target="_blank" external>Support</pharos-sidenav-link>
      <pharos-sidenav-link href="#" target="_blank" external>For Librarians</pharos-sidenav-link>
    </pharos-sidenav-section>
  </pharos-sidenav>
`;

// packages/pharos/src/pages/reports/react/Sidenav.tsx
import type { FC } from 'react';

import { PharosSidenav } from '../../../react-components/sidenav/pharos-sidenav';
import { PharosLink } from '../../../react-components/link/pharos-link';
import { PharosSidenavSection } from '../../../react-components/sidenav/pharos-sidenav-section';
import { PharosSidenavLink } from '../../../react-components/sidenav/pharos-sidenav-link';
import { PharosSidenavMenu } from '../../../react-components/sidenav/pharos-sidenav-menu';

export const Sidenav: FC = () => (
  <PharosSidenav className="reports-page__sidenav">
    <PharosLink slot="top" href="/" id="jstor-logo">
      <img src="./images/jstor-logo-inverse.svg" alt="Pharos Home" width="72" height="100" />
    </PharosLink>
    <PharosSidenavSection>
      <PharosSidenavLink href="#">Home</PharosSidenavLink>
      <PharosSidenavMenu label="Reports" expanded>
        <PharosSidenavLink href="#" isActive>
          COUNTER 5
        </PharosSidenavLink>
        <PharosSidenavLink href="#">Books at JSTOR</PharosSidenavLink>
        <PharosSidenavLink href="#">COUNTER 4</PharosSidenavLink>
      </PharosSidenavMenu>
      <PharosSidenavLink href="#">Holdings</PharosSidenavLink>
      <PharosSidenavLink href="#">Access Methods</PharosSidenavLink>
      <PharosSidenavLink href="#">Account</PharosSidenavLink>
      <PharosSidenavLink href="#" target="_blank" external>
        Support
      </PharosSidenavLink>
      <PharosSidenavLink href="#" target="_blank" external>
        For Librarians
      </PharosSidenavLink>
    </PharosSidenavSection>
  </PharosSidenav>
);
