// packages/pharos/src/pages/item-detail/wc/item-carousel/item-carousel.ts
import { html } from 'lit';
import type { TemplateResult } from 'lit';

import { ItemCarouselItem } from './item-carousel-item';
import { items } from '../../mocks';

import '../../../../components/heading/pharos-heading';
import '../../../../components/button/pharos-button';

export const ItemCarousel = (): TemplateResult => html`
  <div class="item-detail-page__container--top-bar">
    <pharos-heading level="2" preset="3" no-margin>In this collection</pharos-heading>
    <div class="item-detail-page__container--carousel-buttons">
      <pharos-button
        label="backward"
        variant="subtle"
        icon="chevron-left-large"
        icon-condensed
      ></pharos-button>
      <pharos-button
        label="forward"
        variant="subtle"
        icon="chevron-right-large"
        icon-condensed
      ></pharos-button>
    </div>
  </div>
  <ul class="item-detail-page__list item-detail-page__grid--items">
    ${items.map((item) => html`<li>${ItemCarouselItem(item)}</li>`)}
  </ul>
`;

// packages/core/src/pages/item-detail/react/item-carousel/ItemCarousel.tsx
import type { FC } from 'react';
import { Fragment } from 'react';

import { ItemCarouselItem } from './ItemCarouselItem';
import { items } from '../../mocks';

import { PharosButton } from '../../../../react-components/button/pharos-button';
import { PharosHeading } from '../../../../react-components/heading/pharos-heading';

export const ItemCarousel: FC = () => (
  <Fragment>
    <div className="item-detail-page__container--top-bar">
      <PharosHeading level={2} preset="3" noMargin>
        In this collection
      </PharosHeading>
      <div className="item-detail-page__container--carousel-buttons">
        <PharosButton
          label="backward"
          variant="subtle"
          icon="chevron-left-large"
          iconCondensed
        ></PharosButton>
        <PharosButton
          label="forward"
          variant="subtle"
          icon="chevron-right-large"
          iconCondensed
        ></PharosButton>
      </div>
    </div>
    <ul className="item-detail-page__list item-detail-page__grid--items">
      {items.map((item, index) => (
        <li key={index}>{ItemCarouselItem(item)}</li>
      ))}
    </ul>
  </Fragment>
);
