// packages/pharos/src/pages/item-detail/wc/metadata.ts
import { html } from 'lit';
import type { TemplateResult } from 'lit';

import { item, metadata } from '../mocks';

import '../../../components/heading/pharos-heading';

export const Metadata = (): TemplateResult => html`
  <div class="item-detail-page__container--metadata">
    <img
      src="./images/storybook/item-detail/portal-logo.png"
      alt="portal logo"
      class="item-detail-page__image--collection"
    />
    <div class="item-detail-page__label--type">${item.type}</div>
    <pharos-heading level="1" preset="3" class="item-detail-page__heading--metadata"
      >${item.title}</pharos-heading
    >
    <div class="item-detail-page__grid--metadata">
      ${metadata.map(
        (field) => html`
          <div>
            <div class="item-detail-page__label--content">${field.label}</div>
            <span class="item-detail-page__text--metadata">${field.value}</span>
          </div>
        `
      )}
    </div>
  </div>
`;

// packages/pharos/src/pages/item-detail/react/Metadata.tsx
import type { FC } from 'react';

import { item, metadata } from '../mocks';

import { PharosHeading } from '../../../react-components/heading/pharos-heading';

export const Metadata: FC = () => (
  <div className="item-detail-page__container--metadata">
    <img
      src="./images/storybook/item-detail/portal-logo.png"
      alt="portal logo"
      className="item-detail-page__image--collection"
    />
    <div className="item-detail-page__label--type">{item.type}</div>
    <PharosHeading level={1} preset="3" className="item-detail-page__heading--metadata">
      {item.title}
    </PharosHeading>
    <div className="item-detail-page__grid--metadata">
      {metadata.map((field, index) => (
        <div key={index}>
          <div className="item-detail-page__label--content">{field.label}</div>
          <span className="item-detail-page__text--metadata">{field.value}</span>
        </div>
      ))}
    </div>
  </div>
);
